# Generated by Django 5.1.4 on 2025-04-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the demo (e.g., Image Classifier).', max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version (auto-generated).', max_length=220, unique=True)),
                ('description', models.TextField(help_text='A brief description explaining the demo.')),
                ('demo_url_name', models.CharField(help_text="The URL name for the demo view (e.g., 'demos:image_classifier').", max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='URL for a preview image.', max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display on feature lists.')),
                ('is_featured', models.BooleanField(default=True, help_text='Feature this demo on the homepage?')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
    ]
