# Generated by Django 5.2 on 2025-05-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demos', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demo',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='demos', to='skills.skill', verbose_name='Related Skills Showcased'),
        ),
    ]
