# Generated by Django 5.2 on 2025-05-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of the topic.')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order for display.')),
            ],
            options={
                'verbose_name': 'Project Topic',
                'verbose_name_plural': 'Project Topics',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='TopicCategory',
        ),
    ]
