# Generated by Django 5.2 on 2025-04-23 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-date_created']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now, help_text='The date the project entry was created.'),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, help_text='Link to a live demo, if available.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, help_text="Link to the project's GitHub repository.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL for the project's main image or GIF.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which to display projects (lower numbers first).'),
        ),
        migrations.AddField(
            model_name='project',
            name='paper_url',
            field=models.URLField(blank=True, help_text='Link to a relevant paper, if available.', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of key technologies used (e.g., PyTorch, CNN, OpenCV).', max_length=300),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='A detailed description of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='The title of the project.', max_length=200),
        ),
    ]
