# Generated by Django 5.2 on 2025-05-03 15:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
        ('skills', '0001_initial'),
        ('topics', '0002_projecttopic_delete_topic_delete_topiccategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('issuer', models.CharField(max_length=150)),
                ('date_issued', models.DateField(blank=True, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificate_files/')),
                ('logo_image', models.ImageField(blank=True, help_text='Upload a logo image for the issuer or certificate (optional).', null=True, upload_to='certificate_logos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', '-date_issued'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order', '-date_created']},
        ),
        migrations.RemoveField(
            model_name='project',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='project',
            name='image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='technology',
        ),
        migrations.RemoveField(
            model_name='project',
            name='url',
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Key challenges faced during the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='code_language',
            field=models.CharField(blank=True, default='python', help_text='Language for syntax highlighting.', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='An interesting code snippet related to the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='image_url',
            field=models.URLField(blank=True, help_text="URL for the project's main image or GIF.", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Important takeaways or lessons learned.'),
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='paper_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_metrics',
            field=models.TextField(blank=True, help_text='Specific results, metrics, or outcomes achieved.'),
        ),
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill', verbose_name='Associated Skills'),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated).', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text="DEPRECATED: Use 'Skills' field.", max_length=300),
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='projects', to='topics.projecttopic', verbose_name='Project Topics'),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='A detailed description of the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(help_text='The title of the project.', max_length=200),
        ),
    ]
