# Generated by Django 5.2 on 2025-05-03 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_certificate_alter_project_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table=None,
        ),
    ]
