# Generated by Django 5.2 on 2025-04-23 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_options_remove_project_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the title (auto-generated).', max_length=250, unique=True),
        ),
    ]
