# Generated by Django 5.2 on 2025-04-24 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_project_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The name of the certificate or accomplishment.', max_length=250)),
                ('issuer', models.CharField(help_text='The organization that issued the certificate.', max_length=150)),
                ('date_issued', models.DateField(blank=True, help_text='The date the certificate was issued.', null=True)),
                ('credential_url', models.URLField(blank=True, help_text='Link to verify the credential online.', max_length=500, null=True)),
                ('logo_url', models.URLField(blank=True, help_text="URL for the issuer's logo or certificate icon.", max_length=500, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display certificates (lower numbers first).')),
            ],
            options={
                'ordering': ['order', '-date_issued'],
            },
        ),
    ]
