# Generated by Django 5.2 on 2025-05-04 20:01

from django.db import migrations


import os # Import os to read environment variables

def create_superuser(apps, schema_editor):
    """
    Creates the initial superuser account using environment variables.
    """
    User = apps.get_model('auth', 'User') # Use historical model

    # Get credentials from environment variables
    # Set these environment variables locally (e.g., in .env) before running migrate locally
    # And set them in Render's Environment Variables section for deployment
    DJANGO_SUPERUSER_USERNAME = os.environ.get('DJANGO_SUPERUSER_USERNAME', 'admin') # Default to 'admin' if not set
    DJANGO_SUPERUSER_PASSWORD = os.environ.get('DJANGO_SUPERUSER_PASSWORD')
    DJANGO_SUPERUSER_EMAIL = os.environ.get('DJANGO_SUPERUSER_EMAIL', '') # Optional

    if not DJANGO_SUPERUSER_PASSWORD:
        print("\nWarning: DJANGO_SUPERUSER_PASSWORD environment variable not set. Cannot create superuser.")
        return # Exit if password isn't set

    # Check if user already exists
    if User.objects.filter(username=DJANGO_SUPERUSER_USERNAME).exists():
        print(f"\nSuperuser '{DJANGO_SUPERUSER_USERNAME}' already exists. Skipping creation.")
    else:
        print(f"\nCreating superuser '{DJANGO_SUPERUSER_USERNAME}'...")
        User.objects.create_superuser(
            username=DJANGO_SUPERUSER_USERNAME,
            password=DJANGO_SUPERUSER_PASSWORD,
            email=DJANGO_SUPERUSER_EMAIL
        )
        print("Superuser created successfully.")


def remove_superuser(apps, schema_editor):
    """ Optional: Code to run if you ever reverse this migration """
    # You might not need to implement the reverse operation,
    # or you could find and delete the user if necessary.
    pass


class Migration(migrations.Migration):

    dependencies = [
        # Add dependency on the previous migration in the 'portfolio' app
        # Example: ('portfolio', '0003_auto_your_previous_migration'),
        # Or if it's the first migration in portfolio:
        # ('portfolio', '__first__'),
        # IMPORTANT: It MUST also depend on the initial auth migration
        ('auth', '0003_alter_project_table'), # Check latest auth migration number
    ]
