# Generated by Django 5.2 on 2025-04-24 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='logo_url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a logo image (optional).', null=True, upload_to='certificate_logos/'),
        ),
    ]
