# Generated by Django 5.2 on 2025-04-24 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_certificate_logo_url_certificate_logo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='credential_url',
        ),
        migrations.AddField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, help_text='Upload the certificate file (e.g., PDF).', null=True, upload_to='certificate_files/'),
        ),
    ]
