# Generated by Django 5.2 on 2025-04-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_remove_certificate_credential_url_and_more'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='projects', to='skills.skill', verbose_name='Associated Skills'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text="DEPRECATED: Comma-separated list. Use the 'Skills' field instead.", max_length=300),
        ),
    ]
