# Generated by Django 5.2 on 2025-04-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_project_skills_alter_project_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Key challenges faced during the project and how they were addressed.'),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Important takeaways, insights, or lessons learned from the project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='results_metrics',
            field=models.TextField(blank=True, help_text='Specific results, metrics, or outcomes achieved (e.g., accuracy improvement, performance gains).'),
        ),
    ]
