# Generated by Django 5.2 on 2025-04-25 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0008_project_challenges_project_lessons_learned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='code_language',
            field=models.CharField(blank=True, default='python', help_text='Language for syntax highlighting (e.g., python, javascript, html, css, sql).', max_length=50),
        ),
        migrations.AddField(
            model_name='project',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='An interesting code snippet related to the project (paste code here).'),
        ),
    ]
