# Generated by Django 5.2 on 2025-04-26 14:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_projecttopic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='logo_image',
        ),
        migrations.AddField(
            model_name='project',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='projects', to='portfolio.projecttopic', verbose_name='Project Topics'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='certificate_file',
            field=models.FileField(blank=True, null=True, upload_to='certificate_files/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='date_issued',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='issuer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Key challenges faced during the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_language',
            field=models.CharField(blank=True, default='python', help_text='Language for syntax highlighting.', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='code_snippet',
            field=models.TextField(blank=True, help_text='An interesting code snippet related to the project.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='project',
            name='demo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='github_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True, help_text='Important takeaways or lessons learned.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='paper_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='results_metrics',
            field=models.TextField(blank=True, help_text='Specific results, metrics, or outcomes achieved.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='technologies',
            field=models.CharField(blank=True, default='', help_text="DEPRECATED: Use 'Skills' field.", max_length=300),
        ),
    ]
