# Generated by Django 5.1.4 on 2025-04-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_create_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='logo_image',
            field=models.ImageField(blank=True, help_text='Upload a logo image for the issuer or certificate (optional).', null=True, upload_to='certificate_logos/'),
        ),
    ]
