# Generated by Django 5.1.4 on 2025-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the product.', max_length=200)),
                ('description', models.TextField(help_text='Brief description or why you recommend it.')),
                ('product_url', models.URLField(help_text='Link to the product (e.g., store page, affiliate link).', max_length=500)),
                ('image_url', models.URLField(blank=True, help_text='URL for the product image.', max_length=500, null=True)),
                ('category', models.CharField(blank=True, help_text='Optional category (e.g., Book, Course, Software, Hardware).', max_length=100)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which to display products.')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
