# Generated by Django 5.1.4 on 2025-04-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedproduct',
            name='slug',
            field=models.SlugField(blank=True, help_text='URL-friendly version of the name (auto-generated).', max_length=220, unique=True),
        ),
    ]
